import type { Metadata } from "next";
import localFont from "next/font/local";
import Script from 'next/script'
import "./globals.css";
import PathnameWrapper from "components/PathnameWrapper";
import { ToastContainer } from 'react-toastify';
import { Providers } from "./Providers";
import "jsvectormap/dist/css/jsvectormap.css";
import "flatpickr/dist/flatpickr.min.css";
import "../css/satoshi.css";
import "../css/style.css";

const optimaFont = localFont({
  src: "../../public/font/OPTIMA.woff",
})

export const metadata: Metadata = {
  title: "Interior Film",
  description: "Generated by Interior Film",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <Providers>

      <html lang="en">
        <head>
          <Script async src="https://www.googletagmanager.com/gtag/js?id=G-ZNPK8S2CW7"></Script>
          <Script id="google-analytics">
            {
              `window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());

              gtag('config', 'G-ZNPK8S2CW7'); `
            }
          </Script>
        </head>
        <body className={`
        ${optimaFont.className}`}>
          <PathnameWrapper>
            {children}
            <ToastContainer />

          </PathnameWrapper>

        </body>


      </html>
    </Providers>

  );
}
