import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import localFont from "next/font/local";

import "./globals.css";
import PathnameWrapper from "components/PathnameWrapper";

import { ToastContainer } from 'react-toastify';



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Interior Film",
  description: "Generated by Interior Film",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body className={` ${inter.className}`}>
      <PathnameWrapper>
        {children}
        <ToastContainer />

        </PathnameWrapper>

      </body>
    </html>
  );
}
